package com.yesmaster.app

import com.google.gson.JsonObject
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertTrue
import org.junit.Test
import java.io.File

/**
 * Fourth consumer of the repo's wire drift gate: decodes the canonical Rust
 * samples (src/wire-samples.json, generated by src-tauri/tests/wire_shape.rs)
 * through the SAME Gson models the app uses at runtime. A Rust-side field
 * rename now fails this JVM test in addition to the TS compile gate and the
 * Swift/Rust wire pins.
 */
class WireSamplesTest {

    private fun samples(): JsonObject {
        // Gradle runs JVM tests with the module dir as CWD.
        val file = File("../../../src/wire-samples.json").canonicalFile
        assertTrue("wire-samples.json missing at ${file.path}", file.exists())
        return Wire.gson.fromJson(file.readText(), JsonObject::class.java)
    }

    @Test
    fun analysisDecodesTheKeysTheAppReads() {
        val analysis = Wire.analysis(samples()["analysis_result"].toString())
        assertEquals(-14.0, analysis.lufsIntegrated, 1e-9)
        assertEquals(-1.0, analysis.truePeakDbtp, 1e-9)
        assertEquals(8.0, analysis.dynamicRangeLu, 1e-9)
    }

    @Test
    fun renderJobDecodesTheKeysTheAppReads() {
        val job = Wire.renderJob(samples()["render_job"].toString())
        assertEquals(listOf("out/wire-sample.master.wav"), job.outputPaths)
        val measurements = job.measurements
        assertNotNull("measurements missing from render_job sample", measurements)
        assertEquals(-13.5, measurements!!.lufsIntegrated, 1e-9)
        assertEquals(-1.25, measurements.truePeakDbtp, 1e-9)
        assertEquals(8.5, measurements.dynamicRangeLu, 1e-9)
        assertEquals(48_000, measurements.sampleRate)
        assertEquals(24, measurements.bitDepth)
    }

    @Test
    fun styleIdsMatchTheParityFixture() {
        val parity = Wire.gson.fromJson(
            File("../../../src/standard-mapping-parity.json").canonicalFile.readText(),
            JsonObject::class.java,
        )
        val styles = parity["styles"].asJsonObject
        assertEquals(
            styles.keySet(),
            StandardStyle.entries.map { it.id }.toSet(),
        )
        val loudness = parity["loudness"].asJsonObject
        for (step in StandardLoudness.entries) {
            assertEquals(
                "loudness ${step.id} drifted from the parity fixture",
                loudness[step.id].asFloat,
                step.lufs,
                1e-6f,
            )
        }
    }
}
