//! DeliveryProfile parity tripwire (Rust half).
//!
//! The frontend keeps DeliveryProfile lookup records in bindings.ts because
//! those values drive Advanced's profile -> Custom writes. This test emits the
//! Rust methods into src/delivery-profile-parity.json; the TS half asserts the
//! bindings.ts records match it, so profile retunes fail loudly on both sides.

use std::path::Path;

use yes_master_lib::types::DeliveryProfile;

fn profiles() -> Vec<(&'static str, DeliveryProfile)> {
    vec![
        ("streaming-universal", DeliveryProfile::StreamingUniversal),
        ("apple-music", DeliveryProfile::AppleMusic),
        ("cd", DeliveryProfile::Cd),
        ("vinyl-premaster", DeliveryProfile::VinylPremaster),
        ("loud-rock", DeliveryProfile::LoudRock),
        ("broadcast-eu", DeliveryProfile::BroadcastEu),
        ("broadcast-us", DeliveryProfile::BroadcastUs),
        ("custom", DeliveryProfile::Custom),
    ]
}

fn profile_rows() -> serde_json::Value {
    let mut rows = serde_json::Map::new();
    for (id, profile) in profiles() {
        rows.insert(
            id.to_string(),
            serde_json::json!({
                "target_lufs": profile.target_lufs(),
                "ceiling_dbtp": profile.ceiling_dbtp(),
                "bit_depth": profile.output_bit_depth(),
                "sample_rate": profile.output_sample_rate(),
            }),
        );
    }
    serde_json::json!({
        "_readme": "Generated by src-tauri/tests/delivery_profile_parity.rs \
                    from Rust DeliveryProfile methods. Do not edit by hand. \
                    Regenerate after an intentional retune with \
                    YES_MASTER_UPDATE_GOLDEN=1 cargo test --test \
                    delivery_profile_parity, then make npm test green.",
        "profiles": rows,
    })
}

#[test]
fn delivery_profile_parity_json_is_current() {
    let mut actual = serde_json::to_string_pretty(&profile_rows()).expect("serialize profiles");
    actual.push('\n');
    let path = Path::new(env!("CARGO_MANIFEST_DIR")).join("../src/delivery-profile-parity.json");
    if std::env::var("YES_MASTER_UPDATE_GOLDEN").as_deref() == Ok("1") {
        std::fs::write(&path, &actual).expect("write delivery profile parity");
        return;
    }
    let expected = std::fs::read_to_string(&path)
        .expect(
            "src/delivery-profile-parity.json missing - generate it with \
             YES_MASTER_UPDATE_GOLDEN=1 and commit it",
        )
        .replace("\r\n", "\n");
    assert_eq!(
        actual, expected,
        "Rust DeliveryProfile methods changed vs \
         src/delivery-profile-parity.json. If intentional: regenerate with \
         YES_MASTER_UPDATE_GOLDEN=1, commit the fixture, and update bindings.ts \
         until npm test passes."
    );
}
