//! Run explicitly after the independent encoder qualification matrix.
//! Fixtures here are synthetic files generated by verify-audio-encoders.mjs.
use std::path::PathBuf;

#[test]
#[ignore = "requires the qualified sidecar matrix; set YES_MASTER_ENCODER_QUALIFICATION"]
fn new_formats_reimport_through_the_application_decoder() {
    let dir =
        PathBuf::from(std::env::var("YES_MASTER_ENCODER_QUALIFICATION").expect("matrix directory"));
    for rate in [44_100, 48_000] {
        for channels in [1, 2] {
            for frames in [257, rate * 2 + 137] {
                let input = dir.join(format!("signal-{rate}-{channels}-{frames}.wav"));
                let reference = yes_master_lib::decode::decode_full(&input).expect("reference WAV");
                for ext in ["flac", "aiff", "m4a", "aac", "ogg"] {
                    let path = input
                        .with_file_name(format!("signal-{rate}-{channels}-{frames}.wav.{ext}"));
                    let decoded = yes_master_lib::decode::decode_full(&path)
                        .unwrap_or_else(|e| panic!("{}: {e}", path.display()));
                    assert_eq!(decoded.sample_rate, rate);
                    assert_eq!(decoded.channels, channels);
                    assert!(decoded.samples.iter().all(|v| v.is_finite()));
                    assert!(decoded.samples.iter().any(|v| v.abs() > 0.1));
                    if matches!(ext, "flac" | "aiff") {
                        assert_eq!(decoded.samples, reference.samples, "{ext}: PCM changed");
                    }
                }
            }
        }
    }
}
