//! Display-mirror tripwires (Rust half).
//!
//! Two frontend files hand-mirror per-preset calibration values from
//! `dsp.rs`: the compressor table in `src/lib/compressor-auto.ts` and the
//! stereo-width/saturation baselines in `src/components/SignalChain.tsx`.
//! These have drifted before and were only caught by review. This
//! test emits the engine's values into `src/preset-mirrors.json`; TS tests
//! assert the mirrors match, so the next preset retune fails `npm test`
//! instead of silently lying in the UI readouts.
//!
//! These are tripwires, not single-source-of-truth: the engine table stays
//! authoritative in dsp.rs, the UI copies stay display-only, and drift
//! becomes loud. Regenerate after an intentional retune:
//!   $env:YES_MASTER_UPDATE_GOLDEN = "1"; cargo test --test preset_mirrors
//!
//! Values are rounded to 3 decimals so the f32→f64 widening yields the same
//! doubles the TS literals parse to.

use std::path::Path;

use yes_master_lib::dsp::preset_calibration;
use yes_master_lib::types::Preset;

fn round3(v: f32) -> f64 {
    (f64::from(v) * 1000.0).round() / 1000.0
}

fn kinds() -> Vec<(&'static str, Preset)> {
    vec![
        ("universal", Preset::Universal),
        ("clarity", Preset::Clarity),
        ("tape", Preset::Tape),
        ("spatial", Preset::Spatial),
        ("oomph", Preset::Oomph),
        ("warmth", Preset::Warmth),
        ("punch", Preset::Punch),
        ("loud", Preset::Loud),
        (
            "custom",
            Preset::Custom {
                id: "mirror".to_string(),
            },
        ),
    ]
}

fn mirrors() -> serde_json::Value {
    let mut compressor = serde_json::Map::new();
    let mut stereo_width = serde_json::Map::new();
    let mut saturation = serde_json::Map::new();
    for (kind, preset) in kinds() {
        let cal = preset_calibration(&preset);
        compressor.insert(
            kind.to_string(),
            serde_json::json!({
                "threshold_db": round3(cal.compressor_threshold_dbfs),
                "ratio": round3(cal.compressor_ratio),
                "attack_ms": round3(cal.compressor_attack_ms),
                "release_ms": round3(cal.compressor_release_ms),
            }),
        );
        stereo_width.insert(
            kind.to_string(),
            serde_json::json!(round3(cal.stereo_width)),
        );
        saturation.insert(kind.to_string(), serde_json::json!(round3(cal.warmth)));
    }
    serde_json::json!({
        "_readme": "Generated by src-tauri/tests/preset_mirrors.rs from the \
                    dsp.rs PRESET_* calibration — do not edit. Regenerate \
                    after an intentional retune with \
                    YES_MASTER_UPDATE_GOLDEN=1 cargo test --test preset_mirrors, \
                    then make npm test green (compressor-auto + SignalChain \
                    mirrors).",
        "compressor": compressor,
        "saturation": saturation,
        "stereo_width": stereo_width,
    })
}

#[test]
fn preset_mirrors_json_is_current() {
    let mut actual = serde_json::to_string_pretty(&mirrors()).expect("serialize mirrors");
    actual.push('\n');
    let path = Path::new(env!("CARGO_MANIFEST_DIR")).join("../src/preset-mirrors.json");
    if std::env::var("YES_MASTER_UPDATE_GOLDEN").as_deref() == Ok("1") {
        std::fs::write(&path, &actual).expect("write preset mirrors");
        return;
    }
    let expected = std::fs::read_to_string(&path)
        .expect(
            "src/preset-mirrors.json missing — generate it with \
             YES_MASTER_UPDATE_GOLDEN=1 and commit it",
        )
        .replace("\r\n", "\n");
    assert_eq!(
        actual, expected,
        "the dsp.rs preset calibration changed vs the committed \
         src/preset-mirrors.json. If the retune is intentional: regenerate \
         with YES_MASTER_UPDATE_GOLDEN=1, commit the diff, and update the UI \
         mirrors until npm test passes."
    );
}
