// Rust ↔ TS wire-contract drift gate (TypeScript half).
//
// `src/wire-samples.json` is generated by `src-tauri/tests/wire_shape.rs`
// from canonical Rust values of each load-bearing wire type. The exported
// type aliases below compare the JSON key sets against the hand-written
// interfaces in bindings.ts AT COMPILE TIME — they fire in `npm run build`
// (tsc -b), which type-checks this file even though vitest itself does not.
//
// A compile error on one of these aliases names the drifted keys:
//   - `…RustOnly` not never  → Rust emits a key bindings.ts doesn't declare.
//     Add the field to bindings.ts (or, if it is deliberately backend-only,
//     add it to that type's allowlist below with a comment).
//   - `…TsOnly` not never    → bindings.ts declares a key Rust doesn't emit.
//     The frontend would read undefined at runtime; fix bindings.ts or the
//     Rust struct.
//
// After an intentional Rust-side change, regenerate the samples first:
//   $env:YES_MASTER_UPDATE_GOLDEN = "1"; cargo test --test wire_shape

import { describe, expect, it } from "vitest";

import samples from "./wire-samples.json";
import type {
  AdvancedSettings,
  AlbumPlan,
  AlbumTrackEntry,
  AnalysisProgress,
  AnalysisResult,
  CompressionPlan,
  GuardrailReadout,
  LandingStatus,
  MasteringSettings,
  PlaybackTick,
  RenderJob,
  RenderedMeasurements,
} from "./bindings";

type AssertNever<T extends never> = T;
type RustOnly<Sample, Binding> = Exclude<keyof Sample, keyof Binding>;
type TsOnly<Sample, Binding> = Exclude<keyof Binding, keyof Sample>;

export type Drift_AdvancedSettings_RustOnly = AssertNever<
  RustOnly<typeof samples.advanced, AdvancedSettings>
>;
export type Drift_AdvancedSettings_TsOnly = AssertNever<
  TsOnly<typeof samples.advanced, AdvancedSettings>
>;

export type Drift_AlbumPlan_RustOnly = AssertNever<
  RustOnly<typeof samples.album_plan, AlbumPlan>
>;
export type Drift_AlbumPlan_TsOnly = AssertNever<
  TsOnly<typeof samples.album_plan, AlbumPlan>
>;

export type Drift_AlbumTrackEntry_RustOnly = AssertNever<
  RustOnly<typeof samples.album_track_entry, AlbumTrackEntry>
>;
export type Drift_AlbumTrackEntry_TsOnly = AssertNever<
  TsOnly<typeof samples.album_track_entry, AlbumTrackEntry>
>;

export type Drift_AnalysisProgress_RustOnly = AssertNever<
  RustOnly<typeof samples.analysis_progress, AnalysisProgress>
>;
export type Drift_AnalysisProgress_TsOnly = AssertNever<
  TsOnly<typeof samples.analysis_progress, AnalysisProgress>
>;

// Allowlist: `deep_analysis` is backend-internal (profile store + iPhone
// bridge consume it in Rust); bindings.ts mirrors only the FE-relevant
// subset of AnalysisResult on purpose.
export type Drift_AnalysisResult_RustOnly = AssertNever<
  Exclude<RustOnly<typeof samples.analysis_result, AnalysisResult>, "deep_analysis">
>;
export type Drift_AnalysisResult_TsOnly = AssertNever<
  TsOnly<typeof samples.analysis_result, AnalysisResult>
>;

export type Drift_CompressionPlan_RustOnly = AssertNever<
  RustOnly<typeof samples.compression_plan, CompressionPlan>
>;
export type Drift_CompressionPlan_TsOnly = AssertNever<
  TsOnly<typeof samples.compression_plan, CompressionPlan>
>;

export type Drift_GuardrailReadout_RustOnly = AssertNever<
  RustOnly<typeof samples.guardrail_readout, GuardrailReadout>
>;
export type Drift_GuardrailReadout_TsOnly = AssertNever<
  TsOnly<typeof samples.guardrail_readout, GuardrailReadout>
>;

export type Drift_LandingStatus_RustOnly = AssertNever<
  RustOnly<typeof samples.landing_status, LandingStatus>
>;
export type Drift_LandingStatus_TsOnly = AssertNever<
  TsOnly<typeof samples.landing_status, LandingStatus>
>;

export type Drift_MasteringSettings_RustOnly = AssertNever<
  RustOnly<typeof samples.mastering_settings, MasteringSettings>
>;
export type Drift_MasteringSettings_TsOnly = AssertNever<
  TsOnly<typeof samples.mastering_settings, MasteringSettings>
>;

export type Drift_PlaybackTick_RustOnly = AssertNever<
  RustOnly<typeof samples.playback_tick, PlaybackTick>
>;
export type Drift_PlaybackTick_TsOnly = AssertNever<
  TsOnly<typeof samples.playback_tick, PlaybackTick>
>;

export type Drift_RenderJob_RustOnly = AssertNever<
  RustOnly<typeof samples.render_job, RenderJob>
>;
export type Drift_RenderJob_TsOnly = AssertNever<
  TsOnly<typeof samples.render_job, RenderJob>
>;

export type Drift_RenderedMeasurements_RustOnly = AssertNever<
  RustOnly<typeof samples.rendered_measurements, RenderedMeasurements>
>;
export type Drift_RenderedMeasurements_TsOnly = AssertNever<
  TsOnly<typeof samples.rendered_measurements, RenderedMeasurements>
>;

// Runtime smoke so the gate is also visible in `npm test` output (the real
// enforcement is the compile-time block above).
describe("wire-samples drift gate", () => {
  it("covers every gated wire type", () => {
    for (const key of [
      "advanced",
      "album_plan",
      "album_track_entry",
      "analysis_progress",
      "analysis_result",
      "compression_plan",
      "guardrail_readout",
      "landing_status",
      "mastering_settings",
      "playback_tick",
      "render_job",
      "rendered_measurements",
    ]) {
      expect(samples, `missing sample: ${key}`).toHaveProperty(key);
    }
  });

  it("nested samples materialize their optional objects", () => {
    expect(samples.advanced.source_profile).not.toBeNull();
    expect(samples.mastering_settings.album).not.toBeNull();
    expect(samples.render_job.measurements).not.toBeNull();
  });
});
